# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    CI_FLAVOUR: "new" # set to "classic" for old-style CI
    SKIP_PYTHON_TESTS: "not applicable"
    FORCE_RUN_GRID: "yes"

conda-run:
    rules:
        - when: never

check-models:
    extends: .preflight
    script:
        - !reference [.install, nextflow] # requires nextflow to read config
        - bash util/update_models_schema.sh . docker
        - >
            if ! diff nextflow_schema.json nextflow_schema.json.new; then
                echo "Model schema requires updating."
                exit 1
            fi

docker-run:

    # Define a 1D job matrix to inject a variable named MATRIX_NAME into
    #   the CI environment, we can use the value of MATRIX_NAME to determine
    #   which options to apply as part of the rules block below
    # NOTE There is a slightly cleaner way to define this matrix to include
    #   the variables, but it is broken when using long strings! See CW-756
    tags:
        - grid
        - shell
    parallel:
        matrix:
            - MATRIX_NAME: [
                "dorado",
                "watch_path",
                "no_reference"
            ]
    rules:
        # NOTE As we're overriding the rules block for the included docker-run
        #  we must redefine this CI_COMMIT_BRANCH rule to prevent docker-run
        #  being incorrectly scheduled for "detached merge request pipelines" etc.
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never
        - if: $MATRIX_NAME == "dorado"
          variables:
             NF_BEFORE_SCRIPT: "wget -qO demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-basecalling/demo_data.tar.gz && tar -xzvf demo_data.tar.gz && cat demo_data/VERSION && rm demo_data.tar.gz"
             NF_WORKFLOW_OPTS: "--input demo_data/input --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta --basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v4.1.0 --basecaller_chunk_size 1"
             NF_IGNORE_PROCESSES: "stopCondition"
        - if: $MATRIX_NAME == "watch_path"
          variables:
             NF_BEFORE_SCRIPT: "wget -qO demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-basecalling/demo_data.tar.gz && tar -xzvf demo_data.tar.gz && cat demo_data/VERSION && rm demo_data.tar.gz"
             NF_WORKFLOW_OPTS: "--input demo_data/input --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta --basecaller_cfg dna_r10.4.1_e8.2_400bps_sup@v4.1.0 --watch_path --read_limit 3000 --basecaller_chunk_size 1"
        - if: $MATRIX_NAME == "no_reference"
          variables:
             NF_BEFORE_SCRIPT: "wget -qO demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-basecalling/demo_data.tar.gz && tar -xzvf demo_data.tar.gz && cat demo_data/VERSION && rm demo_data.tar.gz"
             NF_WORKFLOW_OPTS: "--input demo_data/input --basecaller_cfg dna_r10.4.1_e8.2_400bps_sup@v4.1.0 --basecaller_chunk_size 1"
             NF_IGNORE_PROCESSES: "cram_cache,stopCondition"

aws-run:
    rules:
        - when: never
